config/routes.rb
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  Rails.application.routes.draw do
  resources :contents do
    resources :translations, except: [:index, :show]
  end

  root "contents#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/content.rb
class Content < ApplicationRecord

  include ActiveModel::Dirty
  has_many :translations, dependent: :destroy

  after_create :init
  after_commit :submit_job

  private

  def init
    self.from_lang = "EN"
  end

  def submit_job
    saved_change = saved_change_to_text?
    TranslateJob.perform_later(self) if saved_change
  end
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :content

  include ActiveModel::Dirty
  after_commit :submit_job

  private

  def submit_job
    saved_change = saved_change_to_to_lang?
    if saved_change
      TranslateJob.perform_later(content)
      puts "******* Running translation job! #{saved_change}"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_content, only: [:show, :edit, :update, :destroy]
  before_action :set_contents, only: [ :create ]

  # GET /contents
  # GET /contents.json
  def index
    @contents = Content.all
    @contentnew = Content.new # For modal "new" form that appears in the bottom of the index form.
    @contentold = Content.all.first # For model "edit" form that appears below it.
  end

  # GET /contents/1
  # GET /contents/1.json
  def show
    @translations = @content.translations
  end

  # GET /contents/new
  def new
    @content = Content.new
  end

  # GET /contents/1/edit
  def edit
  end

  # POST /contents
  # POST /contents.json
  def create
    @content = Content.new(content_params)

    respond_to do |format|
      if @content.save
        format.html { redirect_to contents_url, notice: 'Content was successfully created.' }
        format.json { render :show, status: :created, location: @content }
      else
        format.html { render :new }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contents/1
  # PATCH/PUT /contents/1.json
  def update
    respond_to do |format|
      if @content.update(content_params)
        format.html { redirect_to contents_url, notice: 'Content was successfully updated.' }
        format.json { render :show, status: :ok, location: @content }
      else
        format.html { render :edit }
        format.json { render json: @content.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contents/1
  # DELETE /contents/1.json
  def destroy
    @content.destroy
    respond_to do |format|
      format.html { redirect_to contents_url, notice: 'Content was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  
  def set_content
    @content = Content.find(params[:id])
  end

  def set_contents
    @contents = Content.all
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def content_params
    params.require(:content).permit(:text, :translation, :from_lang, :to_lang)
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  before_action :set_translation, only: [:show, :edit, :update, :destroy]
  before_action :set_content, only: [:new, :create, :edit, :update, :destroy]

  def index
    @translations = Content.find(params[:content_id]).translations
  end

  def show
  end

  def new
   @translation = @content.translations.new
  end

  def edit
  end

  def create
    @translation = @content.translations.build(translation_params)
    respond_to do |format|
      if @translation.save
        format.html { redirect_to content_path(@content), notice: 'Translation was successfully created.' }
        format.json { render :show, status: :created, location: @translation }
      else
        format.html { render :new }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @translation.update(translation_params)
        format.html { redirect_to @content, notice: 'Translation was successfully updated.' }
        format.json { render :show, status: :ok, location: @translation }
      else
        format.html { render :edit }
        format.json { render json: @translation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @translation.destroy
    respond_to do |format|
      format.html { redirect_to @content, notice: 'Translation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_translation
    @translation = Translation.find(params[:id])
  end

# Never trust parameters from the scary internet, only allow the white list through.
  def set_content
    @content = Content.find(params.require(:content_id))
  end

  def translation_params
    params.require(:translation).permit(:content_id, :to_lang)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contents_helper.rb
module ContentsHelper
  def google_language_options
    options_for_select(google_language_list)
  end

  def google_language_list
    [["English", "en"],
      ["French", "fr"],
      ["Spanish", "es"],
      ["Dutch", "nl"],
      ["Arabic", "ar"],
      ["Icelandic", "is"],
      ["Japanese", "ja"],
      ["Italian", "it"],
      ["Hebrew", "iw"]]
  end
end

app/helpers/translations_helper.rb
module TranslationsHelper
end

app/views/contents/_content.html.erb
<tr data-controller="content" data-target="content.contentRow" >
  <td><%= link_to content.text, content, data: {target: "content.rowValue" }  %></td>
  <td><%= content.from_lang%></td>
  <td><%= content.translations.size %> (<%= link_to 'add', new_content_translation_path(content) %>) </td>
  <td><%= link_to 'Edit', edit_content_path(content), remote: true %></td>
  <td><%= link_to 'Destroy', content, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/contents/_content_form_error_section.html.erb
<% if content.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>
    <ul>
      <% content.errors.full_messages.each do |message| %>
        <li>
          <%= message %>
        </li>
        <% end %>
    </ul>
  </div>
<% end %>

app/views/contents/_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :text, "Enter Original Text", class: "label" %>
          <div class="control">
            <%= form.text_area :text, class: "textarea" %>
          </div>
      </div>

      <div class="field">
        <%= form.label :from_lang, "Language of original", class: "label" %>
          <div class="select">
            <%= form.select(:from_lang, google_language_options) %>
          </div>
      </div>

      <div class="actions control">
        <%= form.submit "OK", class:"button is-small" %>
      </div>
      <% end %>

app/views/contents/_modal_content_form.html.erb
<div class="modal is-active">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">New Content</p>
    </header>
    <div class="modal-card-body">
      <%= form_with(model: content, local: true) do |form| %>
        <%= render 'content_form_error_section', content: content %>
        <div class="field">
          <%= form.label :text, "Enter Original Text", class: "label" %>
          <div class="control">
            <%= form.text_area :text, class: "textarea" %>
          </div>
        </div>
        <div class="field">
          <%= form.label :from_lang, "Language of original", class: "field-label" %>
          <div class="select">
            <%= form.select(:from_lang, google_language_options) %>
          </div>
        </div>
        <div class="field is-grouped is-grouped-right">
            <p class="actions control">
              <%= form.submit "OK", class:"button is-success" %>
            </p>
            <p class="control">
              <%= link_to "back", root_path, class: "button" %>
            </p>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/contents/_modal_new.html.erb
<div class="modal" data-target="content.showAddModal">
  <div class="modal-background"></div>
  <div class="modal-card">
    <header class="modal-card-head">
      <p class="modal-card-title">New Content</p>
    </header>
    <section class="modal-card-body">
      <%= render 'form', content: content %>
    </section>
    <footer class="modal-card-foot">
      <button class="button is-success">Save changes</button>
      <button class="button">Cancel</button>
    </footer>
  </div>
</div>

app/views/contents/deleteme/DDD_form.html.erb
<%= form_with(model: content, local: true) do |form| %>
  <% if content.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(content.errors.count, "error") %> prohibited this content from being saved:</h2>

      <ul>
        <% content.errors.full_messages.each do |message| %>
          <li>
            <%= message %>
          </li>
          <% end %>
      </ul>
    </div>
    <% end %>

      <div class="field">
        <%= form.label :text, "Enter Original Text", class: "label" %>
          <div class="control">
            <%= form.text_area :text, class: "textarea" %>
          </div>
      </div>

      <div class="field">
        <%= form.label :from_lang, "Language of original", class: "label" %>
          <div class="select">
            <%= form.select(:from_lang, google_language_options) %>
          </div>
      </div>

      <div class="actions control">
        <%= form.submit "OK", class:"button is-small" %>
      </div>
      <% end %>

app/views/contents/deleteme/edit.html.erb
<% content_for :title_area do %>
  Editing Content
<% end %>

<%= render 'form', content: @content %>

<%= link_to 'Show', @content %> |
<%= link_to 'Back', contents_path %>

app/views/contents/deleteme/new.html.erb
<div class="container">
  <h1 class="title">Original Text</h1>
  <%= render 'form', content: @content %>
  <%= link_to 'cancel', contents_path, class:"button" %>
</div>

app/views/contents/edit.js.erb
console.log("edit button")
document.querySelector(".modal-create").innerHTML = "<%=j render 'modal_content_form', content: @content %>"

app/views/contents/index.html.erb
<% content_for :title_area do %>
  Original Texts
<% end %>
<div>
  <table class="table">
    <thead>
      <tr>
        <th>Original Text</th>
        <th>Language</th>
        <th>Translations</th>
        <th colspan="2">Originals</th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: "content", collection: @contents %>
    </tbody>
  </table>
  <%= link_to "New Original Text Remote", new_content_path, remote: true, class: "button" %>
  <div class="modal-create"></div>
</div>

app/views/contents/new.js.erb
console.log("yes")
document.querySelector(".modal-create").innerHTML = "<%=j render 'modal_content_form', content: @content %>"

app/views/contents/show.html.erb
<% content_for :title_area do %>
  Translations
<% end %>
<h2 class="subtitle">
  <%= @content.from_lang %>: <%= @content.text %>
</h2>
<div class="content">
  <table class="table">
    <tbody>
      <%= render partial: "translations/translation", collection: @translations %>
    </tbody>
  </table>
</div>
<%= link_to 'add another translation', new_content_translation_path(@content), class: "button" %>
<%= link_to 'Back', contents_path, class: "button" %>

app/views/layouts/_root_header.html.erb
<%= csrf_meta_tags %>
<%= csp_meta_tag %>
<meta name="viewport" content="width=device-width, initial-scale=1">

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= action_cable_meta_tag %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
<link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
<script src="https://unpkg.com/stimulus/dist/stimulus.umd.js"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails52demo1</title>
    <%= render 'layouts/root_header' %>
  </head>

  <body>
    <section class="section">
      <div class="container">
        <%= link_to contents_path do %>
          <span class="button icon is-medium" >
            <i class="fas fa-home"></i>
          </span>
        <% end %>
        <h1 class="title">
          <%= yield :title_area %>
        </h1>
          
        <p id="notice"><%= notice %></p>
        <%= yield %>
      </div>
    </section>
  </body>
</html>

app/views/translations/_form.html.erb
<%= form_with(model: @translation, url: [@content, @translation], local: true) do |form| %>
  <% if translation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(translation.errors.count, "error") %> prohibited this translation from being saved:</h2>

      <ul>
      <% translation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label "Target Language", class: "label is-small" %>
    <div class="select"> 
      <%= form.select(:to_lang, google_language_options) %>
    </div>
  </div>

  <div class="field">
    <%= form.label "Original Content" %>
    <%= form.label translation.content.text %>
  </div>

  <div class="field">
    <%= form.label "Translation" %>
    <% if translation.translation.nil? %>
      <em>no translation yet</em>
    <% else %>
      <%= form.label translation.translation %>
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Submit spefication", class: "button" %>
  </div>
<% end %>

app/views/translations/_translation.html.erb
  <tr>
    <td>
      <%= translation.to_lang %>
    </td>
    <td class="translation-text" id="t<%= translation.id %>">
      <%= translation.translation %>
    </td>
    <td>
      <%= link_to 'edit', edit_content_translation_path(@content, translation)  %>
      <%= link_to 'delete', content_translation_path(@content, translation), method: :delete, data: { confirm: 'Are you sure?' } %>
    </td>
  </tr>

app/views/translations/edit.html.erb
<% content_for :title_area do %>
  Editing Translations
<% end %>
<%= render 'form', translation: @translation %>

app/views/translations/index.html.erb
<% content_for :title_area do %>
  translations
<% end %>

<table class="table">
  <thead>
    <tr>
      <th>Translation</th>
      <th>To lang</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%= render "translations" %>
  </tbody>
</table>
  <%= render 'form', translation: @translation %>

app/views/translations/new.html.erb
<% content_for :title_area do %>
  New Translation Specification
<% end %>
<%= render 'form', translation: @translation %>

app/views/translations/show.html.erb
<% content_for :title_area do %>
  Translation
<% end %>
<p>
  <strong>Translation:</strong>
  <%= @translation.translation %>
</p>

<p>
  <strong>To lang:</strong>
  <%= @translation.to_lang %>
</p>

<p>
  <strong>Content:</strong>
  <%= @translation.content %>
</p>

<%= link_to 'Edit', edit_translation_path(@translation) %> |
<%= link_to 'Back', translations_path %>

app/views/translations/v1_translation.html.erb
<div class="card">
  <div class="card-header">
    <div class="card-header-title" %>
      <%= translation.to_lang %>
    </div>
    </div>
  <div class="card-content">
    <div class="content">
      <%= translation.translation %>
    </div>
  </div>
  <div class="card-footer">
    <%= link_to 'delete', edit_content_translation_path(@content, translation), class: "card-footer-item" %>
    <%= link_to 'edit', edit_content_translation_path(@content, translation), class: "card-footer-item"  %>
  </div>
</div>